services:
  postgres:
    image: postgres:14-alpine
    restart: always
    command: postgres -c listen_addresses='*'
    container_name: nowplaying-db
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  nowplaying-grpc:
    image: nowplaying-grpc:latest
    restart: unless-stopped
    container_name: nowplaying-grpc
    build: ynison_proxy
    ports:
      - "50051:50051"
  telegram-bot-api:
    image: ghcr.io/es3n1n/telegram-bot-api:latest
    restart: unless-stopped
    container_name: nowplaying-bot-api
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - tg_data:/var/lib/telegram-bot-api
  bot-api-janitor:
    image: bot-api-janitor:latest
    restart: unless-stopped
    container_name: nowplaying-bot-api-janitor
    build: botapi_janitor
    volumes:
      - tg_data:/var/lib/telegram-bot-api
    environment:
      - TZ=$(cat /etc/timezone)
volumes:
  # Not a directory to avoid errors due to : in filenames on windows
  tg_data:
    name: "nowplaying_tg_data"
