version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    command: postgres -c listen_addresses='*'
    container_name: nowplaying-db
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - internal_network
  nowplaying:
    image: nowplaying-bot:latest
    restart: unless-stopped
    container_name: nowplaying-bot
    build: .
    ports:
      - "31337:1337"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - internal_network
      - udownloader_network
    tmpfs:
      - /tmp

networks:
  internal_network:
    driver: bridge
    internal: true
  udownloader_network:
    name: udownloader
    external: true
