[tool.poetry]
name = "nowplayingbot"
version = "0.1.0"
description = ""
authors = ["es3n1n <me@es3n.in>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.7.0"
httpx = "^0.27.0"
fastapi = "^0.111.0"
uvicorn = "^0.30.1"
loguru = "^0.7.2"
spotipy = "^2.24.0"
psycopg = {extras = ["binary", "pool"], version = "^3.1.19"}
pydantic-settings = "^2.3.3"
filelock = "^3.15.1"
async-lru = "^2.0.4"
aiostream = "^0.6.1"
youtube-dl = {git = "https://github.com/ytdl-org/youtube-dl.git", rev = "0153b387e57e0bb8e580f1869f85596d2767fb0d"}
scdl = {git = "https://github.com/flyingrub/scdl", rev = "42fbc5c23e3331059b05657f0819ac4835d6b83b"}

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
mypy = "^1.10.0"
isort = "^5.13.2"
flake8-quotes = "^3.4.0"
flake8-bugbear = "^24.4.26"

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
lines_after_imports = 2
combine_as_imports = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
