name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: '3.11'

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.4.0/install.sh | sh

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: uv-venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/uv.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: uv sync --dev --frozen --no-install-project

      - name: Type check
        run: uv run mypy nowplaying

      - name: Lint
        run: uv run ruff check --output-format=github

      - name: Format check
        run: uv run ruff format --check

      - name: Run tests
        run: |
          cp .env.example .env
          uv run pytest . --exitfirst
